loja-carros/Models/Carro.cs
namespace loja_carros.Models
{
    public class Carro
    {
        
        public int Id { get; set; }
        public string? Marca { get; set; }
        public string? Modelo { get; set; }
        public int Ano { get; set; }
        public string? Cor { get; set; }
        public float Preco { get; set; }
    }
}

loja-carros/Models/ErrorViewModel.cs
namespace mjv_aula_10.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

loja-carros/Controllers/CarroController.cs
using loja_carros.Dal;
using Microsoft.AspNetCore.Mvc;
using loja_carros.Models;
using System;

public class CarroController : Controller
{
    private readonly IPostgresDal _postgresDal;

    
    

    public CarroController(IPostgresDal postgresDal)
    {
        _postgresDal = postgresDal;
        
    }

    public IActionResult Index()
    {
        var carros = _postgresDal.ListarCarros();
        return View(carros);
    }

    public IActionResult CadastrarCarro()
    {
        return View();
    }

    [HttpPost]
    public IActionResult EnviarCarro(Carro carro)
    {
        if (ModelState.IsValid)
        {
            ViewBag.Mensagem = "Formulário enviado. Carro salvo com sucesso!";
            _postgresDal.InserirCarro(carro.Id,carro.Marca, carro.Modelo, carro.Ano, carro.Cor, carro.Preco);
        }

        return RedirectToAction("Index");
    }
    
    public IActionResult EditarCarro(int id)
    {
        return View();

    }

    [HttpPost]
    public IActionResult AtualizarCarro(Carro carro)
    {
        if (ModelState.IsValid)
        {
            _postgresDal.AtualizarCarro(carro.Id, carro.Marca, carro.Modelo, carro.Ano, carro.Cor, carro.Preco);
        }

        return RedirectToAction("Index");
    }

    public IActionResult DeletarCarro(int id)
    {
        var carro = _postgresDal.SelecionarCarro(id);

        if (carro == null)
        {
            return RedirectToAction("Index");
        }

        return View(carro);
    }

    [HttpPost]
    public IActionResult ExcluirCarroConfirmado(int id)
    {
        _postgresDal.DeletarCarro(id);
        return RedirectToAction("Index");
    }

    public IActionResult Privacy()
    {
        return View();
    }


}

loja-carros/Views/Carro/CadastrarCarro.cshtml
@model List<loja_carros.Models.Carro   >
<div class="container ali mt-4">
    <h2>Cadastrar Veículo </h2>
</div>
<div class="container position-relative">
<div class="row align-items-center">
    <div class="col-md-6">
        <form asp-controller="Carro" asp-action="EnviarCarro" method="post" id="meuForm">

            <div class="form-group row-cols-2 mb-3">

                <label>Marca</label>
                <input type="text" name="Marca" class="form-control-sm" placeholder="Digite a Marca"/>
            </div>
            <div class="form-group row-cols-2 mb-3">
                <label>Modelo</label>
                <input type="text" name="Modelo" class="form-control-sm" placeholder="Digite o Modelo"/>
            </div>
            <div class="form-group row-cols-2 mb-3">
                <label>Ano</label>
                <input type="text" name="Ano" class="form-control-sm" placeholder="Digite o Ano"/>
            </div>
            <div class="form-group row-cols-2 mb-3">
                <label>Cor</label>
                <input type="text" name="Cor" class="form-control-sm" placeholder="Digite a Cor"/>
            </div>
            <div class="form-group row-cols-2 mb-4">
                <label>Preço</label>
                <input type="text" name="Preco" class="form-control-sm" placeholder="Digite o Preço"/>
            </div>
            
            <div>

            <div class="align-items-lg-baseline">

                <button type="submit" class="btn btn-primary btn-md w-50 btn-block mx-auto" value="Confirmar">Salvar</button>
                </div>
                <div class="flex-column">
                    <button type="submit" class="btn btn-outline-danger btn-md w-50 btn-block mt-3" value="Cancelar" asp-controller="Carro" asp-action="Index">Cancelar</button>
                
                </div>

            </div>
        </form>
    </div>
</div>
</div>


@if (ViewBag.Mensagem != null)
{
    <div>
        <p>@ViewBag.Mensagem</p>
        
    </div>
}

loja-carros/Views/Carro/DeletarCarro.cshtml
@model loja_carros.Models.Carro

<h2>Deletar Veículo</h2>

<form asp-controller="Carro" asp-action="ExcluirCarroConfirmado" method="post">
    <input type="hidden" asp-for="Id" />
    
    <p>Você tem certeza de que deseja deletar este veículo?</p>

      <table class="table">
          <tr>
              <td><label asp-for="Marca">Marca:</label></td>
              <td><span>@Model.Marca</span></td>
          </tr>
          <tr>
              <td><label asp-for="Modelo">Modelo:</label></td>
              <td><span>@Model.Modelo</span></td>
          </tr>
          <tr>
              <td><label asp-for="Ano">Ano:</label></td>
              <td><span>@Model.Ano</span></td>
          </tr>
          <tr>
              <td><label asp-for="Cor">Cor:</label></td>
              <td><span>@Model.Cor</span></td>
          </tr>
          <tr>
              <td><label asp-for="Preco">Preço:</label></td>
              <td><span>@Model.Preco</span></td>
          </tr>
      </table>
    <div class="align-content-center">
    <button type="submit" class="btn btn-primary btn-md w-25 btn-block mx-auto" value="Confirmar">Confirmar</button>
    </div>
    <div class="align-items-lg-baseline">
        <button type="submit" class="btn btn-outline-danger  w-25 btn-md btn-block mt-3 mx-auto" value="Cancelar" asp-controller="Carro" asp-action="Index">Cancelar</button>

    
    </div>
</form>

loja-carros/Views/Carro/EditarCarro.cshtml
@model loja_carros.Models.Carro
<div class="align-row justify-content-center-lg-center">
<div class="container ali mt-4">
<h2>Editar Veículo</h2>
</div>
<div class="container position-relative">
    <div class="row align-items-center">
        <div class="col-md-6">
            <form asp-controller="Carro" asp-action="AtualizarCarro" method="post">
                <div class="form-group row-cols-2 mb-3">
                    <label asp-for="Id">Id</label>
                    <input type="text" asp-for="Id" class="form-control-sm" placeholder="Digite o Id" />
                </div>
    
                <div class="form-group row-cols-2 mb-3">
                    <label asp-for="Marca">Marca</label>
                    <input asp-for="Marca" class="form-control-sm" placeholder="Digite a Marca" />
                </div>
    
                <div class="form-group row-cols-2 mb-3">
                    <label asp-for="Modelo">Modelo</label>
                    <input asp-for="Modelo" class="form-control-sm" placeholder="Digite o Modelo" />
                </div>
    
                <div class="form-group row-cols-2 mb-3">
                    <label asp-for="Ano">Ano</label>
                    <input asp-for="Ano" class="form-control-sm" placeholder="Digite o Ano" />
                </div>
    
                <div class="form-group row-cols-2 mb-3">
                    <label asp-for="Cor">Cor</label>
                    <input asp-for="Cor" class="form-control-sm" placeholder="Digite a Cor" />
                </div>
    
                <div class="form-group row-cols-2 mb-3">
                    <label asp-for="Preco">Preço</label>
                    <input asp-for="Preco" class="form-control-sm" placeholder="Digite o Preço" />
                </div>
    
                <div class="align-items-lg-baseline">
        
                    <button type="submit" class="btn btn-primary btn-md w-50 btn-block mx-auto" value="Confirmar">Confirmar</button>
                </div>
                <div class="flex-column">
                    <button type="submit" class="btn btn-outline-danger btn-md w-50 btn-block mt-3" value="Cancelar" asp-controller="Carro" asp-action="Index">Cancelar</button>
                
                </div>
            </form>
    
        </div>
    </div>
</div>

</div>

loja-carros/Views/Carro/Index.cshtml
@model List<loja_carros.Models.Carro>



<table class="table">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Id</th>
        <th scope="col">Modelo</th>
        <th scope="col">Marca</th>
        <th scope="col">Ano</th>
        <th scope="col">Cor</th>
        <th scope="col">Valor</th>
        <th scope="col">Ações</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var carro in Model)
    {
        <tr>
            <th scope="row">@carro.Id</th>
            <td>@carro.Modelo</td>
            <td>@carro.Marca</td>
           
            <td>@carro.Ano</td>
            <td>@carro.Cor</td>
            <td>@string.Format(new System.Globalization.CultureInfo("pt-BR"), "{0:C0}", carro.Preco)</td>

            <td>
<div class="btn-group" role="group" aria-label="Ações">
    <div class="btn-group" role="group" aria-label="Ações">
        <a role="button" class="btn btn-primary mr-2" asp-controller="Carro" asp-action="EditarCarro" asp-route-id="@carro.Id">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5z"/>
            </svg>
        </a>
        <div class="btn-group" role="group" aria-label="Ações">
            <a role="button" class="btn btn-danger" asp-controller="Carro" asp-action="DeletarCarro" asp-route-id="@carro.Id">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                </svg>
            </a>
        </div>
    </div>
</div>

            </td>
        </tr>
    }
    </tbody>
</table>

<div class="text-center">
    <div class="d-grid gap-0=2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Carro" asp-action="CadastrarCarro">
            
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
            </svg> 
            Adicionar
        </a>
    </div>
</div>

loja-carros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]MK MOTORS</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>*@
    <link rel="stylesheet" href="~/css/mycss.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/mjv_aula_10.styles.css" asp-append-version="true"/>
</head>
<body>
<header class="mb-4">
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Carro" asp-action="Index">MK MOTORS</a>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
            <div class="collapse navbar-collapse" id="navbarColor02">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link active" asp-area="" asp-controller="Carro" asp-action="Index">Home</a>
                        <span class="visually-hidden"></span>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Carro" asp-action="CadastrarCarro">Cadastrar</a>
                    </li>
                                        <li class="nav-item">
                                            <a class="nav-link" asp-area="" asp-controller="Carro" asp-action="EditarCarro">Atualizar</a>
                                            </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Carro" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container text-center">
        &copy; 2023 - MK MOTORS - Todos os direitos reservados -  <a asp-area="" asp-controller="Carro" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
@*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>